"use client";

/**
 * Presentation "Plan" view — the polished, print-ready 2D floor plan generated by the backend
 * from the UBM (GET /ubm/svg): pastel rooms, name + area, dimension lines, door swings and
 * furniture. Read-only; the Edit view remains the place to change geometry.
 */
import { useEffect, useState } from "react";
import { FileWarning } from "lucide-react";
import { useAuthStore } from "@/store";
import { BuildingLoader } from "@/components/ui/building-loader";

export function PlanView({ pid, dirty }: { pid: number; dirty: boolean }) {
  const token = useAuthStore((s) => s.token);
  const [svg, setSvg] = useState<string | null>(null);
  const [err, setErr] = useState(false);

  useEffect(() => {
    let alive = true;
    setSvg(null);
    setErr(false);
    fetch(`/api/projects/${pid}/ubm/svg`, { headers: token ? { Authorization: `Bearer ${token}` } : {} })
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
      .then((t) => alive && setSvg(t))
      .catch(() => alive && setErr(true));
    return () => {
      alive = false;
    };
  }, [pid, token]);

  if (err)
    return (
      <div className="grid h-full w-full place-items-center bg-[#f7f8fa] text-center text-sm text-muted-foreground">
        <div className="space-y-2">
          <FileWarning className="mx-auto size-8 text-amber-500" />
          <p>Build the model first to preview the plan.</p>
        </div>
      </div>
    );
  if (!svg) return <div className="grid h-full w-full place-items-center bg-[#f7f8fa]"><BuildingLoader /></div>;

  return (
    <div className="relative h-full w-full overflow-auto bg-[#f7f8fa]">
      {dirty && (
        <div className="pointer-events-none absolute left-1/2 top-2 z-10 -translate-x-1/2 rounded-full bg-amber-100 px-3 py-1 text-[11px] font-medium text-amber-800 shadow-sm">
          Showing last saved plan — Save to refresh
        </div>
      )}
      <div
        className="flex h-full w-full items-center justify-center p-4 [&_svg]:h-full [&_svg]:w-full"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </div>
  );
}
